# ==========================
# Fonts
# ==========================
# font_family      JetBrainsMono Nerd Font
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size        13

disable_ligatures never

# ==========================
# Cursor
# ==========================
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0
cursor_trail 2

# ==========================
# Window
# ==========================
window_padding_width 12
hide_window_decorations yes
window_border_width 0
placement_strategy center

confirm_os_window_close 0

# ==========================
# Transparency
# ==========================
background_opacity 0.94
dynamic_background_opacity yes

# ==========================
# Scrolling
# ==========================
scrollback_lines 20000
wheel_scroll_multiplier 5

# ==========================
# Selection
# ==========================
copy_on_select yes
strip_trailing_spaces smart

# ==========================
# Mouse
# ==========================
mouse_hide_wait 1.5
focus_follows_mouse no

# ==========================
# Bell
# ==========================
enable_audio_bell no
visual_bell_duration 0

# ==========================
# Tabs
# ==========================
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2
tab_separator " "

active_tab_font_style bold
inactive_tab_font_style normal

# ==========================
# Performance
# ==========================
repaint_delay 10
input_delay 3
sync_to_monitor yes

# ==========================
# Theme
# ==========================
include current-theme.conf


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS